M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Wed 02 Mar 2022 06:06:05 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-02T18:06:05-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1575
%
G90
G05
T1
X1.7362Y-1.2583
X1.7362Y-1.4
T2
X1.6Y-1.8445
X1.6Y-2.7445
X2.0Y-1.8445
X2.0Y-2.7445
T3
X1.8Y-1.8445
X1.8Y-2.7445
T0
M30
